name: 'oilgas_demo'
config-version: 2

profile: 'oilgas_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  oilgas_demo:
    +materialized: view
    +meta:
      owner: "Analytics Team"
      project: "Oil & Gas Services dbt Fusion Demo"
      
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
      +meta:
        layer: "staging"
        description: "Raw data transformed with light cleaning and type casting"
        
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ["intermediate"]
      +meta:
        layer: "intermediate"
        description: "Purpose-built transformations for downstream marts"
        
    marts:
      +materialized: table
      +tags: ["marts"]
      +meta:
        layer: "marts"
        description: "Business-facing analytics tables"
        
      core:
        +tags: ["core", "marts"]
        +meta:
          subdomain: "core"
          description: "Core business entities and fact tables"
          
      finance:
        +tags: ["finance", "marts"]
        +meta:
          subdomain: "finance"
          description: "Financial reporting and revenue analytics"
          
      operations:
        +tags: ["operations", "marts"]
        +meta:
          subdomain: "operations"
          description: "Operational metrics and dashboards"

seeds:
  oilgas_demo:
    +schema: raw
    +tags: ["seeds"]
    +meta:
      source_system: "demo_data"

snapshots:
  oilgas_demo:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at
    +tags: ["snapshots"]

vars:
  # Fusion-compatible variable definitions
  start_date: '2023-01-01'
  current_year: 2024
  
  # Custom schema suffixes
  schema_staging: 'staging'
  schema_intermediate: 'intermediate'
  schema_marts: 'analytics'
  
  # Business logic variables
  active_rig_threshold_days: 30
  safety_incident_severity_levels: ['Low', 'Medium', 'High', 'Critical']

# Fusion-ready: No Python models, no deprecated syntax
# All arbitrary configs moved to meta dictionary
# Using modern dbt syntax throughout
